import {supabase,transaction} from './cloud';
import * as pdfjs from 'pdfjs-dist';
pdfjs.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();
import React,{useEffect,useMemo,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{PDFDocument,StandardFonts,rgb}from'pdf-lib';
import{House,Folder,FolderPlus,FileText,Image as ImageIcon,Upload,Search,Grid2X2,List,MoreHorizontal,Download,Trash2,Pencil,Move,Tags,Files,ChevronRight,ChevronLeft,X,Check,Plus,ArrowLeft,RotateCcw,Menu,Eye,CheckSquare,AlignLeft,FilePlus,GripVertical,Settings,LogOut,Camera,UserRound,Share2,Mail,Copy,ShieldCheck}from'lucide-react';
import './style.css';

const uid=()=>crypto.randomUUID(),extension=n=>(n.split('.').pop()||'').toLowerCase(),fmt=b=>b<1024?b+' B':b<1048576?(b/1024).toFixed(1)+' KB':(b/1048576).toFixed(1)+' MB';
const types=['pdf','txt','png','jpg','jpeg'];
function friendly(e){return e==='pdf'?'PDF':e==='txt'?'TXT':['png','jpg','jpeg'].includes(e)?'Imagem':'Arquivo'}
function safeName(n){return(n||'Documento').replace(/[\\/:*?"<>|]/g,'-').trim()||'Documento'}
const palette=['#e8b96d','#91b9b5','#aaa0dc','#e2a6a3','#86a8d1','#c4a0bc'];
function IconFile({file,size=24}){const ext=extension(file.name);return ext==='pdf'?<FileText size={size} color="#c36963"/>:ext==='txt'?<AlignLeft size={size} color="#76a18c"/>:<ImageIcon size={size} color="#8098c9"/>}
function Library({onLogout,user}){
 const [profileMenu,setProfileMenu]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[categoryMenu,setCategoryMenu]=useState(null);
 const [workspaceId,setWorkspaceId]=useState(user.id),[workspaces,setWorkspaces]=useState([]),[shares,setShares]=useState([]),[shareOpen,setShareOpen]=useState(false),[inviteEmail,setInviteEmail]=useState(''),[inviteRole,setInviteRole]=useState('viewer'),[inviting,setInviting]=useState(false);
 const canEdit=workspaceId===user.id||workspaces.some(w=>w.owner_id===workspaceId&&w.role==='editor');
 const [categoryColor,setCategoryColor]=useState('#aaa0dc');
 const [hexInput,setHexInput]=useState('#aaa0dc');
 const [moveFolder,setMoveFolder]=useState(''),[moveCategory,setMoveCategory]=useState(''),[categoryPickerOpen,setCategoryPickerOpen]=useState(false),[savingMove,setSavingMove]=useState(false);
 const [items,setItems]=useState([]),[folder,setFolder]=useState(null),[view,setView]=useState('grid'),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState([]),[modal,setModal]=useState(null),[draft,setDraft]=useState(''),[preview,setPreview]=useState(null),[mergeOrder,setMergeOrder]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[menu,setMenu]=useState(null),[sidebar,setSidebar]=useState(false),[drag,setDrag]=useState(false);
 const pick=useRef(null);
 const refresh=async()=>setItems(await transaction('all',null,workspaceId));useEffect(()=>{setItems([]);setFolder(null);setFilter('all');setSelected([]);refresh().catch(e=>message('Falha ao carregar espaço: '+e.message))},[workspaceId]);
 useEffect(()=>{loadWorkspaces().catch(console.error)},[]);
 async function loadWorkspaces(){const {data,error}=await supabase.from('hd_shares').select('*').order('created_at',{ascending:false});if(error)throw error;setWorkspaces(data.filter(x=>x.owner_id!==user.id));setShares(data.filter(x=>x.owner_id===user.id))}
 async function sendInvite(e){e.preventDefault();if(!inviteEmail.trim())return;setInviting(true);try{const email=inviteEmail.trim().toLowerCase();if(email===user.email?.toLowerCase())throw Error('Você já é dono deste espaço.');const {error}=await supabase.from('hd_shares').upsert({owner_id:user.id,invitee_email:email,role:inviteRole,workspace_name:user.user_metadata?.full_name||user.email?.split('@')[0]||'Espaço compartilhado'},{onConflict:'owner_id,invitee_email'});if(error)throw error;await loadWorkspaces();const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Sessão expirada. Entre novamente.');const response=await fetch('/api/send-invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({email,role:inviteRole})});const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error||'Não foi possível enviar e-mail.');setInviteEmail('');message('Convite enviado por e-mail para '+email)}catch(err){message('Acesso salvo, mas envio não concluído: '+err.message)}finally{setInviting(false)}}
 async function removeShare(share){if(!window.confirm('Revogar acesso de '+share.invitee_email+'?'))return;const {error}=await supabase.from('hd_shares').delete().eq('id',share.id);if(error)message(error.message);else{await loadWorkspaces();message('Acesso revogado.')}}
 const message=t=>{setNotice(t);setTimeout(()=>setNotice(''),4500)};
 const folders=items.filter(x=>x.kind==='folder'&&!x.deleted),categories=items.filter(x=>x.kind==='category'&&!x.deleted),files=items.filter(x=>x.kind==='file'&&!x.deleted),trash=items.filter(x=>x.deleted);
 const current=folders.find(x=>x.id===folder);
 const visibleFolders=folders.filter(x=>x.parent===folder&&(!query||x.name.toLowerCase().includes(query.toLowerCase()))&&filter==='all');
 const visibleFiles=files.filter(x=>(filter==='trash'?false:filter==='all'?x.folder===folder:filter==='uncategorized'?!x.category:filter===x.category)&&(!query||x.name.toLowerCase().includes(query.toLowerCase())));
 const inTrash=filter==='trash';
 const shownFiles=inTrash?trash.filter(x=>x.kind==='file'):visibleFiles;
 const byId=id=>items.find(x=>x.id===id);
 async function save(item){await transaction('put',item,workspaceId);await refresh()}
 async function change(id,changes){const i=byId(id);if(i)await save({...i,...changes})}
 function goFolder(id){setFolder(id);setFilter('all');setSelected([]);setQuery('');setSidebar(false)}
 function select(id){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 function startModal(type,item){if(!canEdit)return;setMenu(null);if(type==='move'){setMoveFolder(item.folder||'');setMoveCategory(item.category||'');setCategoryPickerOpen(false)}setDraft(type==='rename'||type==='editCategory'?item.name:'');setCategoryColor(type==='category'?palette[2]:(item?.color||palette[0]));setHexInput(type==='category'?palette[2]:(item?.color||palette[0]));setModal({type,item})}
 async function create(){const value=draft.trim();if(!value)return;const type=modal.type; if(type==='rename'){await change(modal.item.id,{name:safeName(value)});message('Nome atualizado.')}else if(type==='editCategory'){await change(modal.item.id,{name:safeName(value),color:categoryColor});message('Categoria atualizada.')}else{await save({id:uid(),kind:type==='folder'?'folder':'category',name:safeName(value),parent:type==='folder'?folder:null,color:type==='category'?categoryColor:palette[Math.floor(Math.random()*palette.length)],created:Date.now(),deleted:false});message(type==='folder'?'Pasta criada.':'Categoria criada.')}setModal(null);setDraft('')}
 async function deleteCategory(item){if(!window.confirm('Excluir a categoria "'+item.name+'"? Os documentos serão mantidos sem categoria.'))return;try{for(const file of items.filter(x=>x.kind==='file'&&x.category===item.id)){await transaction('put',{...file,category:null},workspaceId)}await transaction('delete',item.id,workspaceId);if(filter===item.id)setFilter('all');setCategoryMenu(null);await refresh();message('Categoria excluída. Documentos preservados.')}catch(e){message('Não foi possível excluir: '+e.message)}}
 async function addFiles(list){const chosen=Array.from(list||[]);if(!chosen.length||!canEdit)return;setBusy(true);let count=0;for(const f of chosen){if(!types.includes(extension(f.name))){message('Formato não aceito: '+f.name);continue}try{await transaction('put',{id:uid(),kind:'file',name:safeName(f.name),folder,category:null,blob:f,size:f.size,mime:f.type,created:Date.now(),deleted:false},workspaceId);count++}catch(e){message('Falha ao salvar '+f.name+'. Verifique o espaço disponível.')}}await refresh();setBusy(false);if(count)message(count+' arquivo(s) salvo(s).')}
 useEffect(()=>{const handler=e=>{if(e.target.closest('input,textarea,[contenteditable=true]'))return;const clip=e.clipboardData?.files;if(clip?.length)addFiles(clip)};document.addEventListener('paste',handler);return()=>document.removeEventListener('paste',handler)},[folder,workspaceId,canEdit]);
 function download(file){const url=URL.createObjectURL(file.blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function openFile(file){setPreview(file)}
 async function erase(id){await change(id,{deleted:true});setSelected(s=>s.filter(x=>x!==id));message('Movido para a lixeira.')}
 async function restore(id){await change(id,{deleted:false});message('Arquivo restaurado.')}
 async function removeForever(id){await transaction('delete',id,workspaceId);await refresh();message('Excluído permanentemente.')}
 const chosen=selected.map(byId).filter(x=>x?.kind==='file'&&!x.deleted);
 function startMerge(){if(!canEdit)return;setMergeOrder(chosen.map(x=>x.id));setDraft('Documentos reunidos.pdf');setModal({type:'merge'})}
 async function merge(){if(mergeOrder.length<2)return;setBusy(true);try{const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);for(const id of mergeOrder){const item=byId(id),ext=extension(item.name),bytes=new Uint8Array(await item.blob.arrayBuffer());if(ext==='pdf'){const source=await PDFDocument.load(bytes);const pages=await pdf.copyPages(source,source.getPageIndices());pages.forEach(p=>pdf.addPage(p))}else if(ext==='png'||ext==='jpg'||ext==='jpeg'){const img=ext==='png'?await pdf.embedPng(bytes):await pdf.embedJpg(bytes);const d=img.scale(1),page=pdf.addPage([595.28,841.89]),scale=Math.min((page.getWidth()-48)/d.width,(page.getHeight()-48)/d.height,1);page.drawImage(img,{x:(page.getWidth()-d.width*scale)/2,y:(page.getHeight()-d.height*scale)/2,width:d.width*scale,height:d.height*scale})}else if(ext==='txt'){const str=await item.blob.text(),lines=str.replace(/\r/g,'').split('\n');let page=pdf.addPage([595.28,841.89]),y=800;for(const line of lines){const normalized=line.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,'?');const chunks=normalized.match(/.{1,85}/g)||[''];for(const chunk of chunks){if(y<48){page=pdf.addPage([595.28,841.89]);y=800}page.drawText(chunk,{x:36,y,size:10,font,color:rgb(.2,.2,.2)});y-=15}}}}const bytes=await pdf.save(),name=safeName(draft.replace(/\.pdf$/i,''))+'.pdf',blob=new Blob([bytes],{type:'application/pdf'});await save({id:uid(),kind:'file',name,folder,category:null,blob,size:blob.size,mime:'application/pdf',created:Date.now(),deleted:false});setModal(null);setSelected([]);message('PDF criado com sucesso.')}catch(e){console.error(e);message('Não foi possível unir os documentos. Verifique se o PDF não está protegido.')}finally{setBusy(false)}}
 function itemMenu(item){return <div className="menu-options" onClick={e=>e.stopPropagation()}><button onClick={()=>{setMenu(null);item.kind==='folder'?goFolder(item.id):openFile(item)}}><Eye size={16}/> Abrir</button>{canEdit&&<button onClick={()=>startModal('rename',item)}><Pencil size={16}/> Renomear</button>}{item.kind==='file'&&<>{canEdit&&<button onClick={()=>startModal('move',item)}><Move size={16}/> Mover / categorizar</button>}<button onClick={()=>{download(item);setMenu(null)}}><Download size={16}/> Baixar</button></>}{canEdit&&<button className="danger" onClick={()=>{erase(item.id);setMenu(null)}}><Trash2 size={16}/> Excluir</button>}</div>}
 function tile(item){const isFolder=item.kind==='folder',checked=selected.includes(item.id),cat=categories.find(c=>c.id===item.category),accent=cat?.color;return <div key={item.id} className={'tile '+(checked?'checked ':'')+(view==='list'?'as-list':'')} style={accent?{'--cat-accent':accent,borderColor:accent+'88'}:undefined} onContextMenu={e=>{e.preventDefault();e.stopPropagation();setMenu(item.id)}} onClick={()=>isFolder?goFolder(item.id):openFile(item)}>
 <div className={'thumbnail '+(isFolder?'folder-thumb':'')}>{isFolder?<Folder size={42} strokeWidth={1.6} fill={item.color||palette[0]} color={item.color||palette[0]}/>:<Thumbnail file={item} accent={accent}/>}</div>
 <div className="tile-caption"><span className="tile-name" title={item.name}>{item.name}</span><small>{isFolder?'Pasta':friendly(extension(item.name))+' · '+fmt(item.size)}</small>{cat&&<span className="category-chip" style={{color:cat.color,background:cat.color+'20'}}><i style={{background:cat.color}}/>{cat.name}</span>}</div>
 {canEdit&&!isFolder&&!inTrash&&<button className={'select '+(checked?'active':'')} title="Selecionar" onClick={e=>{e.stopPropagation();select(item.id)}}>{checked?<Check size={13}/>:null}</button>}
 <div className="options-wrap" onClick={e=>e.stopPropagation()}><button className="more" title="Opções" onClick={e=>{e.stopPropagation();setMenu(menu===item.id?null:item.id)}}><MoreHorizontal size={19}/></button>{menu===item.id&&itemMenu(item)}</div>
 </div>}
 return <div className="app" onClick={()=>{if(menu)setMenu(null)}}>
 <aside className={'sidebar '+(sidebar?'expanded':'')}><div className="brand" onClick={()=>goFolder(null)}><div className="logo"><House size={19}/></div><span>home<b>.docs</b></span></div><div className="nav-title">ESPAÇOS</div><div className="space-switcher"><button className={'nav space-option '+(workspaceId===user.id?'active':'')} onClick={()=>setWorkspaceId(user.id)}><House size={17}/> <span>Meu espaço</span></button>{workspaces.map(w=><button key={w.id} className={'nav space-option '+(workspaceId===w.owner_id?'active':'')} onClick={()=>setWorkspaceId(w.owner_id)} title={w.workspace_name||'Espaço compartilhado'}><Share2 size={17}/><span>{w.workspace_name||'Espaço compartilhado'}</span></button>)}</div><div className="nav-title section-title library-label">BIBLIOTECA</div><button className={'nav '+(filter==='all'?'active':'')} onClick={()=>{setFolder(null);setFilter('all');setSidebar(false);setSelected([])}}><Folder size={18}/> Meus arquivos</button><button className={'nav '+(filter==='uncategorized'?'active':'')} onClick={()=>{setFilter('uncategorized');setFolder(null);setSidebar(false)}}><FileText size={18}/> Sem categoria</button><div className="nav-title section-title">CATEGORIAS {canEdit&&<button onClick={()=>startModal('category')} title="Nova categoria"><Plus size={17}/></button>}</div>{categories.map(c=><div className="category-nav-wrap" key={c.id} onContextMenu={e=>{if(!canEdit)return;e.preventDefault();setCategoryMenu(categoryMenu===c.id?null:c.id)}}><button className={'nav cat '+(filter===c.id?'active':'')} onClick={()=>{setFilter(c.id);setFolder(null);setSidebar(false);setCategoryMenu(null)}}><i style={{background:c.color}}/>{c.name}</button>{canEdit&&categoryMenu===c.id&&<div className="category-context-menu"><button onClick={()=>{setCategoryMenu(null);startModal('editCategory',c)}}><Pencil size={15}/> Editar categoria</button><button className="danger" onClick={()=>deleteCategory(c)}><Trash2 size={15}/> Excluir categoria</button></div>}</div>)}<div className="aside-bottom"><button className={'nav '+(inTrash?'active':'')} onClick={()=>{setFilter('trash');setFolder(null);setSidebar(false)}}><Trash2 size={18}/> Lixeira</button><div className="aside-note">Arquivos protegidos e sincronizados<br/>pelo Supabase.</div></div></aside>
 <main className="content" onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDrag(false)}} onDrop={e=>{e.preventDefault();setDrag(false);addFiles(e.dataTransfer.files)}}>
 <header className="topbar"><button className="mobile-menu" onClick={()=>setSidebar(!sidebar)}><Menu size={21}/></button><div className="crumb"><button onClick={()=>goFolder(null)}>Biblioteca</button>{current&&<><ChevronRight size={15}/><span>{current.name}</span></>}</div><div className="profile-area"><button type="button" className="share-trigger" onClick={()=>{setShareOpen(true);loadWorkspaces()}}><Share2 size={16}/><span>Compartilhar espaço</span></button><button type="button" className="avatar-trigger" aria-label="Abrir menu do perfil" aria-expanded={profileMenu} onClick={()=>setProfileMenu(v=>!v)}><Avatar user={user}/></button>{profileMenu&&<div className="profile-dropdown"><div className="profile-identity"><strong>{user.email}</strong><small>Minha conta</small></div><button onClick={()=>{setSettingsOpen(true);setProfileMenu(false)}}><Settings size={16}/> Configurações</button><button onClick={()=>{setProfileMenu(false);onLogout()}}><LogOut size={16}/> Sair da conta</button></div>}</div></header>
 <section className="heading"><div><h1>{inTrash?'Lixeira':filter==='uncategorized'?'Sem categoria':filter!=='all'?categories.find(c=>c.id===filter)?.name:current?.name||'Minha biblioteca'}</h1><p>Seus arquivos organizados, do seu jeito.</p></div></section>
 <div className="controls"><div className="search-box"><Search size={18}/><input placeholder="Buscar pastas e documentos..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}><X size={16}/></button>}</div><div className="switch"><button title="Grade" className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 size={18}/></button><button title="Lista" className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={18}/></button></div><div className="top-actions">{canEdit&&<><button className="subtle-btn" onClick={()=>startModal('folder')}><FolderPlus size={17}/> <span>Nova pasta</span></button><button className="primary-btn" onClick={()=>pick.current?.click()}><Plus size={18}/> Adicionar arquivos</button><input type="file" multiple accept=".pdf,.txt,.png,.jpg,.jpeg" ref={pick} style={{display:'none'}} onChange={e=>{addFiles(e.target.files);e.target.value=''}}/></>}</div></div>
 {canEdit&&selected.length>0&&!inTrash&&<div className="selection-bar"><strong>{selected.length} selecionado(s)</strong><button onClick={()=>setSelected([])}>Limpar</button><button className="primary-btn" disabled={chosen.length<2} onClick={startMerge}><Files size={17}/> Juntar documentos</button></div>}
 {!inTrash&&visibleFolders.length>0&&<section className="section"><div className="section-heading"><h2>Pastas</h2><span>{visibleFolders.length}</span></div><div className={'tiles '+view}>{visibleFolders.map(tile)}</div></section>}
 <section className="section"><div className="section-heading"><h2>{inTrash?'Itens excluídos':'Documentos'}</h2><span>{shownFiles.length}</span></div>{shownFiles.length?<div className={'tiles '+view}>{shownFiles.map(item=>inTrash?<div key={item.id} className="trash-item"><IconFile file={item}/><span>{item.name}</span>{canEdit&&<><button onClick={()=>restore(item.id)}>Restaurar</button><button onClick={()=>removeForever(item.id)}>Excluir definitivamente</button></>}</div>:tile(item))}</div>:<div className="empty"><div><Files size={38} strokeWidth={1.3}/></div><h3>{inTrash?'A lixeira está vazia':'Nenhum documento por aqui'}</h3><p>{inTrash?'Os arquivos excluídos aparecem aqui.':'Envie um PDF, imagem ou TXT para começar.'}</p>{!inTrash&&canEdit&&<button className="primary-btn" onClick={()=>pick.current?.click()}><Upload size={16}/> Adicionar arquivos</button>}</div>}</section>
 {drag&&<div className="drop-overlay"><Upload size={44}/><h2>Solte seus documentos aqui</h2></div>}
 </main>
 {shareOpen&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setShareOpen(false)}}><div className="dialog share-dialog"><div className="dialog-header"><h2>Compartilhar espaço</h2><button onClick={()=>setShareOpen(false)} aria-label="Fechar"><X size={19}/></button></div>{workspaceId!==user.id?<p className="hint">Este espaço foi compartilhado com você. Apenas o proprietário pode convidar pessoas.</p>:<><p className="hint">Conceda acesso à sua biblioteca inteira. Compartilhamentos podem ser revogados.</p><form onSubmit={sendInvite} className="share-form"><label>E-mail do convidado</label><input type="email" required placeholder="pessoa@exemplo.com" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/><label>Permissão</label><select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="viewer">Visualizar — somente leitura</option><option value="editor">Editor — pode alterar documentos</option></select><button className="primary-btn" disabled={inviting}><Mail size={16}/>{inviting?'Preparando convite...':'Compartilhar e enviar convite'}</button></form><div className="share-members"><h3>Pessoas com acesso</h3>{shares.length===0?<p>Nenhum convite enviado.</p>:shares.map(x=><div className="share-person" key={x.id}><div><strong>{x.invitee_email}</strong><small>{x.role==='editor'?'Editor':'Visualizador'}</small></div><button onClick={()=>removeShare(x)} title="Revogar acesso"><X size={16}/></button></div>)}</div></>}</div></div>}
 {settingsOpen&&<ProfileSettings user={user} close={()=>setSettingsOpen(false)}/>}
 {notice&&<div className="toast">{notice}</div>}
 {busy&&<div className="busy">Processando documentos...</div>}
 {preview&&<Preview file={preview} close={()=>setPreview(null)} download={()=>download(preview)} rename={()=>{startModal('rename',preview);setPreview(null)}}/>}
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="dialog"><div className="dialog-header"><h2>{modal.type==='folder'?'Nova pasta':modal.type==='category'?'Nova categoria':modal.type==='rename'?'Renomear':modal.type==='editCategory'?'Editar categoria':modal.type==='move'?'Organizar documento':'Juntar documentos'}</h2><button onClick={()=>setModal(null)}><X size={20}/></button></div>
 {['folder','category','rename','editCategory'].includes(modal.type)&&<form onSubmit={e=>{e.preventDefault();create()}}><label>Nome</label><input autoFocus value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Digite um nome"/>{['category','editCategory'].includes(modal.type)&&<><label>Cor da categoria</label><div className="color-row">{palette.map(color=><button key={color} type="button" title={color} className={'color-choice '+(categoryColor===color?'chosen':'')} style={{background:color}} onClick={()=>{setCategoryColor(color);setHexInput(color)}}>{categoryColor===color&&<Check size={17} color="#fff"/>}</button>)}<label className="custom-color">Personalizada <input type="color" value={categoryColor} onChange={e=>{setCategoryColor(e.target.value);setHexInput(e.target.value)}}/></label><label className="hex-field">HEX <input type="text" maxLength={7} spellCheck={false} placeholder="#9674C3" value={hexInput} onChange={e=>{const value=e.target.value;setHexInput(value);if(/^#[0-9a-fA-F]{6}$/.test(value))setCategoryColor(value.toLowerCase())}} onBlur={()=>{if(!/^#[0-9a-fA-F]{6}$/.test(hexInput))setHexInput(categoryColor)}}/></label></div></>}<div className="dialog-actions"><button type="button" className="subtle-btn" onClick={()=>setModal(null)}>Cancelar</button><button className="primary-btn">Salvar</button></div></form>}
 {modal.type==='move'&&<div className="form"><label>Pasta</label><select value={moveFolder} onChange={e=>setMoveFolder(e.target.value)}><option value="">Biblioteca (raiz)</option>{folders.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select><label>Categoria</label><div className="category-picker" style={{position:"relative",width:"100%"}}><button type="button" className="category-picker-trigger" style={{display:"flex",alignItems:"center",justifyContent:"space-between",width:"100%",minHeight:43,padding:"0 12px",border:"1px solid #dfe4eb",borderRadius:9,background:"#fff",textAlign:"left"}} onClick={()=>setCategoryPickerOpen(v=>!v)}><span className="category-option-label" style={{display:"flex",alignItems:"center",gap:9}}>{moveCategory&&categories.find(c=>c.id===moveCategory)?<><i style={{background:categories.find(c=>c.id===moveCategory)?.color||'#aaa0dc'}}/>{categories.find(c=>c.id===moveCategory)?.name}</>:<>Sem categoria</>}</span><ChevronRight size={15} className={categoryPickerOpen?'picker-chevron open':'picker-chevron'}/></button>{categoryPickerOpen&&<div className="category-picker-list" style={{position:"absolute",top:"calc(100% + 5px)",left:0,right:0,zIndex:200,display:"flex",flexDirection:"column",maxHeight:240,overflowY:"auto",padding:5,background:"#fff",border:"1px solid #e3e7ed",borderRadius:10,boxShadow:"0 12px 25px #18213220"}}><button type="button" className={moveCategory===''?'picked':''} style={{display:"flex",alignItems:"center",justifyContent:"space-between",width:"100%",padding:"9px 10px",textAlign:"left",borderRadius:7}} onClick={()=>{setMoveCategory('');setCategoryPickerOpen(false)}}><span className="category-option-label"><i className="no-category-color"/>Sem categoria</span>{moveCategory===''&&<Check size={15}/>}</button>{categories.map(c=><button key={c.id} type="button" className={moveCategory===c.id?'picked':''} style={{display:"flex",alignItems:"center",justifyContent:"space-between",width:"100%",padding:"9px 10px",textAlign:"left",borderRadius:7}} onClick={()=>{setMoveCategory(c.id);setCategoryPickerOpen(false)}}><span className="category-option-label"><i style={{background:c.color||'#aaa0dc'}}/>{c.name}</span>{moveCategory===c.id&&<Check size={15}/>}</button>)}</div>}</div><div className="dialog-actions"><button type="button" className="subtle-btn" onClick={()=>setModal(null)}>Cancelar</button><button type="button" className="primary-btn" disabled={savingMove} onClick={async()=>{setSavingMove(true);try{await change(modal.item.id,{folder:moveFolder||null,category:moveCategory||null});setModal(null);message('Documento organizado com sucesso.')}catch(e){message('Erro ao salvar: '+e.message)}finally{setSavingMove(false)}}}>{savingMove?'Salvando...':'Concluir'}</button></div></div>}
 {modal.type==='merge'&&<div className="form"><p className="hint">Organize os documentos na ordem desejada. Os originais serão preservados.</p><div className="merge-files">{mergeOrder.map((id,index)=><div className="merge-row" key={id}><GripVertical size={16}/><span>{index+1}. {byId(id)?.name}</span><button disabled={index===0} onClick={()=>setMergeOrder(o=>{const a=[...o];[a[index-1],a[index]]=[a[index],a[index-1]];return a})}>↑</button><button disabled={index===mergeOrder.length-1} onClick={()=>setMergeOrder(o=>{const a=[...o];[a[index+1],a[index]]=[a[index],a[index+1]];return a})}>↓</button></div>)}</div><label>Nome do PDF final</label><input value={draft} onChange={e=>setDraft(e.target.value)}/><div className="dialog-actions"><button className="subtle-btn" onClick={()=>setModal(null)}>Cancelar</button><button className="primary-btn" disabled={busy||!draft.trim()} onClick={merge}><Files size={16}/> Gerar PDF</button></div></div>}
 </div></div>}
 </div>
}
function Thumbnail({file,accent}){
 const ext=extension(file.name),[src,setSrc]=useState(null);
 useEffect(()=>{let active=true,url=null,task=null;setSrc(null);
 (async()=>{try{
 if(['png','jpg','jpeg'].includes(ext)){url=URL.createObjectURL(file.blob);if(active)setSrc(url)}
 else if(ext==='pdf'&&file.blob){
 const bytes=await file.blob.arrayBuffer();
 task=pdfjs.getDocument({data:new Uint8Array(bytes)});
 const doc=await task.promise;
 const page=await doc.getPage(1),viewport=page.getViewport({scale:1});
 const scale=Math.min(360/viewport.width,460/viewport.height,1.7);
 const view=page.getViewport({scale});
 const canvas=document.createElement('canvas');canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);
 await page.render({canvasContext:canvas.getContext('2d'),viewport:view}).promise;
 if(active)setSrc(canvas.toDataURL('image/png'));
 await doc.destroy();
 }
 }catch(e){console.warn('Miniatura indisponível',e)}})();
 return()=>{active=false;if(url)URL.revokeObjectURL(url)};
 },[file.blob,file.name,ext]);
 return src?<img className={ext==='pdf'?'pdf-cover':''} src={src} alt={'Prévia de '+file.name}/>:<IconFile file={file} size={39}/>;
}
function Preview({file,close,download,rename}){const [url,setUrl]=useState(null),[text,setText]=useState('');const ext=extension(file.name);useEffect(()=>{const u=URL.createObjectURL(file.blob);setUrl(u);if(ext==='txt')file.blob.text().then(setText);return()=>URL.revokeObjectURL(u)},[file]);return <div className="viewer"><div className="viewer-top"><button onClick={close}><ArrowLeft size={20}/></button><div className="viewer-name"><strong>{file.name}</strong><small>{friendly(ext)} · {fmt(file.size)}</small></div><button onClick={rename} title="Renomear"><Pencil size={19}/></button><button onClick={download} title="Baixar"><Download size={19}/></button><button onClick={close} title="Fechar"><X size={21}/></button></div><div className="viewer-body">{url&&(ext==='pdf'?<iframe src={url+'#toolbar=1'} title={file.name}/>:ext==='txt'?<pre>{text}</pre>:<img src={url} alt={file.name}/>)}</div></div>}

function Avatar({user}){
 const [url,setUrl]=useState(null);
 const path=user?.user_metadata?.avatar_path;
 useEffect(()=>{let active=true,objectUrl;setUrl(null);if(!path)return;
 supabase.storage.from('home-docs').download(path).then(({data,error})=>{if(!error&&data&&active){objectUrl=URL.createObjectURL(data);setUrl(objectUrl)}}).catch(()=>{});
 return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)};
 },[path,user?.user_metadata?.avatar_updated_at]);
 return url?<img src={url} alt="Foto de perfil" className="avatar-photo"/>:<UserRound size={22}/>;
}
async function compressAvatar(file){
 if(!file.type.startsWith('image/'))throw Error('Selecione uma imagem válida.');
 const bitmap=await createImageBitmap(file);
 try{
 const scale=Math.min(1,512/Math.max(bitmap.width,bitmap.height));
 const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);
 canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);
 let quality=.82,blob;
 do{blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));quality-=.12}while(blob&&blob.size>200000&&quality>.28);
 if(!blob)throw Error('Não foi possível processar a imagem.');
 return blob;
 }finally{bitmap.close()}
}
function ProfileSettings({user,close}){
 const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[photoPreview,setPhotoPreview]=useState(null);
 const input=useRef(null),localUrl=useRef(null);
 useEffect(()=>()=>{if(localUrl.current)URL.revokeObjectURL(localUrl.current)},[]);
 async function photo(file){
  if(!file)return;setBusy(true);setFeedback('');
  try{
   const blob=await compressAvatar(file);
   const path=user.id+'/profile/avatar.jpg';
   const {error}=await supabase.storage.from('home-docs').upload(path,blob,{upsert:true,contentType:'image/jpeg',cacheControl:'0'});
   if(error)throw error;
   const {error:authError}=await supabase.auth.updateUser({data:{avatar_path:path,avatar_updated_at:Date.now()}});
   if(authError)throw authError;
   if(localUrl.current)URL.revokeObjectURL(localUrl.current);
   localUrl.current=URL.createObjectURL(blob);setPhotoPreview(localUrl.current);setFeedback('Foto de perfil salva na nuvem.');
  }catch(e){setFeedback('Erro ao salvar foto: '+e.message)}
  finally{setBusy(false)}
 }
 async function updatePassword(e){
  e.preventDefault();if(password.length<8){setFeedback('A senha deve ter pelo menos 8 caracteres.');return}if(password!==confirm){setFeedback('As senhas não coincidem.');return}
  setBusy(true);setFeedback('');
  try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;setPassword('');setConfirm('');setFeedback('Senha atualizada com sucesso.')}
  catch(e){setFeedback(e.message)}finally{setBusy(false)}
 }
 return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="dialog settings-dialog"><div className="dialog-header"><h2>Configurações</h2><button onClick={close} aria-label="Fechar"><X size={20}/></button></div>
 <div className="settings-avatar-line"><div className="settings-avatar">{photoPreview?<img src={photoPreview} alt="Nova foto"/>:<Avatar user={user}/>}</div><div><strong>Foto de perfil</strong><p>JPG, PNG ou WebP. A imagem é comprimida automaticamente.</p><button className="subtle-btn" disabled={busy} onClick={()=>input.current?.click()}><Camera size={15}/> Alterar foto</button><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{photo(e.target.files?.[0]);e.target.value=''}}/></div></div>
 <form onSubmit={updatePassword} className="settings-password"><h3>Alterar senha</h3><label>Nova senha</label><input type="password" minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required/><label>Confirmar senha</label><input type="password" minLength={8} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/><button className="primary-btn" disabled={busy}>Salvar nova senha</button></form>
 {feedback&&<p role="status" className="settings-feedback">{feedback}</p>}</div></div>;
}

function App(){
 const [user,setUser]=useState(undefined),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[feedback,setFeedback]=useState(''),[register,setRegister]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user||null)).catch(()=>setUser(null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>subscription.unsubscribe()},[]);
 async function submit(e){e.preventDefault();setLoading(true);setFeedback('');try{const result=register?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(register&&!result.data.session)setFeedback('Confira seu e-mail para confirmar o cadastro.')}catch(e){setFeedback(e.message)}finally{setLoading(false)}}
 if(user===undefined)return <div className="auth-screen">Conectando à home.docs...</div>;
 if(!user)return <div className="auth-screen"><form className="auth-card" onSubmit={submit}><div className="auth-logo"><House size={22}/></div><h1>home<span>.docs</span></h1><p>Sua biblioteca de documentos na nuvem.</p><label>E-mail</label><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/><label>Senha</label><input type="password" required minLength={6} autoComplete={register?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha"/>{feedback&&<div className="auth-feedback">{feedback}</div>}<button className="primary-btn" disabled={loading}>{loading?'Aguarde...':register?'Criar conta':'Entrar'}</button><button type="button" className="auth-toggle" onClick={()=>{setRegister(!register);setFeedback('')}}>{register?'Já possui conta? Entrar':'Não possui conta? Criar cadastro'}</button></form></div>;
 return <Library key={user.id} user={user} onLogout={async()=>{await supabase.auth.signOut();setUser(null)}}/>;
}
createRoot(document.getElementById('root')).render(<App/>);
