import React,{useEffect,useRef,useState} from 'react';
import * as pdfjs from 'pdfjs-dist';
import{PDFDocument,StandardFonts,rgb}from'pdf-lib';
import{Plus,Type,Square,Trash2,ChevronLeft,ChevronRight,Save,X}from'lucide-react';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).toString();
function hexToRgb(hex){const val=hex.replace('#','');return rgb(parseInt(val.slice(0,2),16)/255,parseInt(val.slice(2,4),16)/255,parseInt(val.slice(4,6),16)/255)}
export default function PdfEditor({file,onSave,onCancel}){
 const canvas=useRef(null),[doc,setDoc]=useState(null),[page,setPage]=useState(1),[count,setCount]=useState(1),[marks,setMarks]=useState([]),[tool,setTool]=useState('text'),[text,setText]=useState('Novo texto'),[size,setSize]=useState(18),[color,setColor]=useState('#20242c'),[font,setFont]=useState('Helvetica'),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true,task;const load=async()=>{try{task=pdfjs.getDocument({data:new Uint8Array(await file.blob.arrayBuffer())});const pdf=await task.promise;if(active){setDoc(pdf);setCount(pdf.numPages)}}catch(e){if(active)setError('Não foi possível abrir este PDF para edição.')}};load();return()=>{active=false;if(task)task.destroy().catch(()=>{})}},[file.blob]);
 useEffect(()=>{if(!doc||!canvas.current)return;let cancelled=false;let renderTask;async function render(){try{const p=await doc.getPage(page),initial=p.getViewport({scale:1});const scale=Math.min(1.5,Math.max(.45,750/initial.width));const v=p.getViewport({scale});const c=canvas.current;if(!c||cancelled)return;c.width=Math.round(v.width);c.height=Math.round(v.height);renderTask=p.render({canvasContext:c.getContext('2d'),viewport:v});await renderTask.promise}catch(e){if(!cancelled&&e?.name!=='RenderingCancelledException')setError('Falha ao exibir a página.')}}render();return()=>{cancelled=true;renderTask?.cancel()}},[doc,page]);
 const current=marks.filter(m=>m.page===page);
 function place(e){if(!doc)return;const rect=e.currentTarget.getBoundingClientRect();const x=Math.min(.97,Math.max(0,(e.clientX-rect.left)/rect.width)),y=Math.min(.97,Math.max(0,(e.clientY-rect.top)/rect.height));if(tool==='text'&&!text.trim()){setError('Digite o texto antes de inseri-lo.');return}setMarks(v=>[...v,{id:crypto.randomUUID(),page,x,y,type:tool,text,size:Number(size),color,font}]);setError('')}
 async function save(){if(!marks.length){setError('Adicione alguma alteração antes de salvar.');return}setSaving(true);setError('');try{const pdf=await PDFDocument.load(await file.blob.arrayBuffer());const pages=pdf.getPages();const fonts={};for(const mark of marks){const pg=pages[mark.page-1];if(!pg)continue;const w=pg.getWidth(),h=pg.getHeight(),x=mark.x*w,y=(1-mark.y)*h;if(mark.type==='cover'){pg.drawRectangle({x,y:y-24,width:Math.min(w-x,170),height:26,color:rgb(1,1,1)});continue}const fontId=mark.font==='TimesRoman'?StandardFonts.TimesRoman:mark.font==='Courier'?StandardFonts.Courier:StandardFonts.Helvetica;if(!fonts[fontId])fonts[fontId]=await pdf.embedFont(fontId);const safe=mark.text.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,'?');pg.drawText(safe.slice(0,500),{x,y:y-mark.size,size:mark.size,font:fonts[fontId],color:hexToRgb(mark.color),maxWidth:Math.max(1,w-x-8),lineHeight:mark.size*1.3})}const bytes=await pdf.save();const blob=new Blob([bytes],{type:'application/pdf'});await onSave(blob); }catch(e){setError('Erro ao salvar PDF: '+e.message)}finally{setSaving(false)}}
 return <div className="pdf-editor"><div className="pdf-editor-tools"><div className="pdf-editor-group"><button className={tool==='text'?'active':''} onClick={()=>setTool('text')}><Type size={16}/> Texto</button><button className={tool==='cover'?'active':''} onClick={()=>setTool('cover')}><Square size={16}/> Cobrir</button></div><input aria-label="Texto a adicionar" value={text} onChange={e=>setText(e.target.value)} disabled={tool!=='text'} placeholder="Texto para inserir"/><select value={font} onChange={e=>setFont(e.target.value)} aria-label="Fonte"><option value="Helvetica">Helvetica</option><option value="TimesRoman">Times</option><option value="Courier">Courier</option></select><input type="number" min="8" max="72" value={size} onChange={e=>setSize(Math.max(8,Math.min(72,Number(e.target.value)||12)))} title="Tamanho da fonte" aria-label="Tamanho da fonte"/><input type="color" value={color} onChange={e=>setColor(e.target.value)} title="Cor do texto" aria-label="Cor do texto"/><button onClick={()=>setMarks(m=>m.slice(0,-1))} disabled={!marks.length}><Trash2 size={15}/> Desfazer</button><button className="primary-btn" onClick={save} disabled={saving||!marks.length}><Save size={16}/>{saving?'Salvando...':'Salvar'}</button><button onClick={onCancel} aria-label="Cancelar edição"><X size={18}/></button></div><div className="pdf-editor-hint">Clique na página para {tool==='text'?'adicionar o texto':'cobrir visualmente um trecho com branco'}. O conteúdo original coberto permanece no PDF.</div>{error&&<div className="pdf-editor-error" role="alert">{error}</div>}<div className="pdf-editor-workspace"><div className="pdf-editor-sheet" onClick={place}><canvas ref={canvas}/>{current.map(m=><div key={m.id} className={'pdf-editor-mark '+(m.type==='cover'?'cover':'')} style={{left:(m.x*100)+'%',top:(m.y*100)+'%',fontSize:Math.max(10,m.size*(canvas.current?.clientWidth||700)/(canvas.current?.width||700))+'px',color:m.color,fontFamily:m.font==='TimesRoman'?'Georgia':m.font==='Courier'?'monospace':'Arial'}}>{m.type==='cover'?'':m.text}</div>)}</div></div><div className="pdf-editor-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button>Página {page} de {count}<button disabled={page>=count} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button><span>{marks.length} alteração(ões)</span></div></div>;
}
